version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      GID: 1235
      UID: 1235
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      VERSION: "1.20.1"
      ONLINE_MODE: "FALSE"
      EULA: "TRUE"
      MEMORY: "4G"
      SEED: "-7255571058704538969"
      MAX_PLAYERS: 6
      SERVER_NAME: "server.camp"
      DIFICULTY: "NORMAL"
      MOTD: "Camp Server"
      ICON: "https://github.com/maldex/McServerCompanion/blob/main/templates/server-icon.png?raw=true"
#      OPS: "ops,dont,work,in,offline,mode"
      ENABLE_WHITELIST: "FALSE"
      ENFORCE_WHITELIST: "FALSE"
      ENABLE_RCON: "TRUE" 
      RCON_PORT: 25575
      RCON_PASSWORD: changeme_iam_a_password
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data:z
  backups:
    image: itzg/mc-backup
    environment:
      GID: 1235
      UID: 1235
      BACKUP_INTERVAL: "8h"
      PRUNE_BACKUPS_DAYS: "7"
      RCON_HOST: "mc"
      PAUSE_IF_NO_PLAYERS: "true"
    volumes:
    - ./data:/data:ro,z
    - ./backups:/backups:z
